### ISSUE TITLE
An item with the same key has already been added

### ISSUE THREAD

**Issue by geoffbeaumont** [KS-DB-Merge-Tools/Issues#3]
Getting a lot of "An item with the same key has already been added." errors when trying to generate scripts from the Batch Data Diff (MsSqlMerge, v1.26.0).

I wasn't getting this with the older version I had, but upgraded to fix another bug and ran into this.

I'm repeatedly running the script generation removing tables as they come up, but it's starting to look like there may be no tables left...

I'm getting this error even with tables that don't have any data that needs to be synced (see in screenshot attached - UFUserGroupFormSecurity can be seen to have no rows in either database.

![mssqlmerge-item-with-same-key](https://github.com/KS-DB-Merge-Tools/Issues/assets/3082468/ff3f121a-af4c-4344-96dd-23eb69abc792)

**Comment by geoffbeaumont** [comment]
Further to this - the error seems to appear whenever a table has been selected which doesn't have any work to do (so, a table with no data differences, or one with no new rows if new only is selected).

The workaround is to manually go through deselecting those tables after clicking select all, before generating the script.

**Comment by semenenkov** [comment]
@geoffbeaumont thanks a lot, I've reproduced the issue. It fails on the second table from the list which has an identity column and no work to do. And it was broken with the fix for multiple IDENTITY_INSERTs. I'll release a fix today/tomorrow.

**Comment by semenenkov** [comment]
fixed in 1.26.1
